export default {
    imCurrentLocation: require("../Images/Oval.png"),
    imMarker: require("../Images/greenMarker.png"),
    imIndicator: require("../Images/greenIndicator.png"),
    imCar: require("../Images/car.png"),
    imWork: require("../Images/workLogo.png"),
    imHome: require("../Images/homeLogo.png"),
    imUser: require("../Images/userLogo.png"),
    imBackLogo: require("../Images/backLogo.png"),
    imRoutes: require("../Images/routesLogo.png"),
    imCarLogo: require("../Images/carLogo.png"),
    imLogo: require("../Images/NavigateXLOGO.png"),
    imBackGround: require("../Images/mapBackground.jpg"),
    imHouse: require("../Images/house.png"),
    imSuitcase: require("../Images/suitcase.png"),
    imBack: require("../Images/back.png"),
}
